### ISSUE TITLE
cant find tensorflow-macos

### ISSUE THREAD

**Issue by loicsauteur** [DBM-MCF/efficientv2-unet#5]
on Mac `pip install -e .`
Error:
```
pip install tensorflow-macos==2.11.0
ERROR: Could not find a version that satisfies the requirement tensorflow-macos==2.11.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-macos==2.11.0
```

**Comment by loicsauteur** [comment]
https://medium.com/@jarondlk/installing-tensorflow-metal-on-apple-silicon-macos-with-miniconda-f43121fe3054

**Comment by loicsauteur** [comment]
from https://stackoverflow.com/questions/72964800/what-is-the-proper-way-to-install-tensorflow-on-apple-m1-in-2022

**Fix #: Add conda-forge as a channel, use the legacy optimizer in your code.**
```
conda config --add channels conda-forge
conda config --set channel_priority strict 
 
conda create -y --name cv
conda activate cv
conda install -y -c apple tensorflow-deps
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal

python --version
conda list|grep -E '(tensorflow|numpy)'
```

**Fix 2: Add conda-forge as a channel, pin the version numbers to avoid the pluggable architecture issue.**
```
conda config --add channels conda-forge
conda config --set channel_priority strict 
 
conda create -y --name cv
conda activate cv
conda install -y -c apple tensorflow-deps==2.10.0
python -m pip install tensorflow-macos==2.10.0
python -m pip install tensorflow-metal==0.6.0

python --version
conda list|grep -E '(tensorflow|numpy)'
```
**Fix 3: Don't add conda-forge, pin the version numbers way back to the last ones that actually worked:**
```
conda create -y --name cv python
conda activate cv
conda install -y -c apple tensorflow-deps==2.9.0
python -m pip install tensorflow-macos==2.9.2
python -m pip install tensorflow-metal==0.5.1

python --version
conda list|grep -E '(tensorflow|numpy)'
```

But hopefully, doing `conda install -c apple tensorflow-deps --force-reinstall` is enough?

**Comment by loicsauteur** [comment]
Just `pip install tensorflow-macos==2.11.0` gives (when trying to import tensorflow):

```
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. This error is frequently encountered on macOS when running an x86 Python installation on ARM hardware. In this case, try installing an ARM build of Python. Otherwise, you may be able work around this issue by building jaxlib from source.
```

**Comment by ewelinabartoszek** [comment]
```
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ewelina/opt/anaconda3/envs/ev2unet/lib/python3.9/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
  File "/Users/ewelina/opt/anaconda3/envs/ev2unet/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 17, in <module>
    import ctypes
  File "/Users/ewelina/opt/anaconda3/envs/ev2unet/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/ewelina/opt/anaconda3/envs/ev2unet/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
  Referenced from: <6A25E2DB-80CB-34F0-B5D2-E08664A6D5E1> /Users/ewelina/opt/anaconda3/envs/ev2unet/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
  Reason: tried: '/Users/ewelina/opt/anaconda3/envs/ev2unet/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/Users/ewelina/opt/anaconda3/envs/ev2unet/lib/python3.9/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/Users/ewelina/opt/anaconda3/envs/ev2unet/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/Users/ewelina/opt/anaconda3/envs/ev2unet/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)
```

**Comment by loicsauteur** [comment]
Problems were due to the python environment manager. 
Because the mac was migrated from intel-based to silicon. 
Python would be set up for `x86_64` rather than `arm64`. 

Installing the arm-based environment manager resolved those issues.
